### ISSUE TITLE
Broken toolchain: cannot link a simple C program

### ISSUE THREAD

**Issue by theazlan89** [VahidTa/firewall_migration_tool#4]
Hi i got below errors

\numpy\distutils\command\build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
        File "numpy\core\setup.py", line 676, in get_mathlib_info
          raise RuntimeError("Broken toolchain: cannot link a simple C program")
      RuntimeError: Broken toolchain: cannot link a simple C program

**Comment by VahidTa** [comment]
Which method do you want to implement? Docker or source code? this error related to packages installations.

**Comment by theazlan89** [comment]
I have downloaded the ZIP file and extract it. I follow the instructions from "Bash" step , its source right? I'm using windows, I have tried using MacOS also failed.

**Comment by theazlan89** [comment]
C:\firewall_migration_tool-main>pip install -r requirements.txt
Collecting aniso8601==8.0.0
  Using cached aniso8601-8.0.0-py2.py3-none-any.whl (43 kB)
Collecting bcrypt==3.2.0
  Using cached bcrypt-3.2.0-cp36-abi3-win_amd64.whl (28 kB)
Collecting certifi==2020.12.5
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting cffi==1.14.4
  Using cached cffi-1.14.4.tar.gz (471 kB)
  Preparing metadata (setup.py) ... done
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting cryptography==3.3.1
  Using cached cryptography-3.3.1-cp36-abi3-win_amd64.whl (1.5 MB)
Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting idna==2.10
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting ipaddress==1.0.23
  Using cached ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Collecting itsdangerous==1.1.0
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2==2.11.2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting lxml==4.6.2
  Using cached lxml-4.6.2.tar.gz (3.2 MB)
  Preparing metadata (setup.py) ... done
Collecting MarkupSafe==1.1.1
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting ncclient==0.6.9
  Using cached ncclient-0.6.9.tar.gz (118 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.20.1
  Using cached numpy-1.20.1.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [247 lines of output]
      setup.py:66: RuntimeWarning: NumPy 1.20.1 may not yet support Python 3.10.
        warnings.warn(
      Running from numpy source directory.
      setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\tools\cythonize.py:67: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.version import LooseVersion
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\bit_generator.pyx
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Processing numpy/random\_pcg64.pyx
      Processing numpy/random\_philox.pyx
      Processing numpy/random\_sfc64.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\system_info.py:1989: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      blas_info:
        libraries blas not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\system_info.py:1989: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      blas_src_info:
        NOT AVAILABLE

      C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\system_info.py:1989: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
        NOT AVAILABLE

      non-existing path in 'numpy\\distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      openblas_lapack_info:
        libraries openblas not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      openblas_clapack_info:
        libraries openblas,lapack not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      flame_info:
        libraries flame not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries tatlas,tatlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries lapack_atlas not found in C:\
        libraries tatlas,tatlas not found in C:\
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
        libraries tatlas,tatlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries satlas,satlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries lapack_atlas not found in C:\
        libraries satlas,satlas not found in C:\
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
        libraries satlas,satlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries lapack_atlas not found in C:\
        libraries ptf77blas,ptcblas,atlas not found in C:\
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries f77blas,cblas,atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\lib
        libraries lapack_atlas not found in C:\
        libraries f77blas,cblas,atlas not found in C:\
        libraries lapack_atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
        libraries f77blas,cblas,atlas not found in C:\Users\user\AppData\Local\Programs\Python\Python310\libs
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
        libraries lapack not found in ['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\libs']
        NOT AVAILABLE

      C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\system_info.py:1849: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\system_info.py:1849: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
        NOT AVAILABLE

      numpy_linalg_lapack_lite:
        FOUND:
          language = c
          define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

      C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win32-3.10
      creating build\src.win32-3.10\numpy
      creating build\src.win32-3.10\numpy\distutils
      building library "npymath" sources
      LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-5l0k0mzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-5l0k0mzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-5l0k0mzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 513, in <module>
          setup_package()
        File "setup.py", line 505, in setup_package
          setup(**metadata)
        File "C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\core.py", line 169, in setup
          return old_setup(**new_attr)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-5l0k0mzo\overlay\Lib\site-packages\setuptools\__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-5l0k0mzo\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
          egg_info.run()
        File "C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\command\egg_info.py", line 24, in run
          self.run_command("build_src")
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\command\build_src.py", line 144, in run
          self.build_sources()
        File "C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\command\build_src.py", line 155, in build_sources
          self.build_library_sources(*libname_info)
        File "C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\command\build_src.py", line 288, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "C:\Users\user\AppData\Local\Temp\pip-install-3x6pgs2k\numpy_2b4166ddf96b432eb28fe97c74aef0cb\numpy\distutils\command\build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
        File "numpy\core\setup.py", line 676, in get_mathlib_info
          raise RuntimeError("Broken toolchain: cannot link a simple C program")
      RuntimeError: Broken toolchain: cannot link a simple C program

**Comment by VahidTa** [comment]
You are using python3.10. Please re-check with python3.8

**Comment by VahidTa** [comment]
Thats great! I am closing this issue and you can update previous issue #3
