### ISSUE TITLE
Failed to open app.py

### ISSUE THREAD

**Issue by theazlan89** [VahidTa/firewall_migration_tool#5]
Hi,

I try run app.py but failed. Below is the errors

Traceback (most recent call last):
  File "C:\Github\firewall_migration_tool-main\app.py", line 3, in <module>
    from flask import Flask, flash, request, redirect, url_for, send_from_directory
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\__init__.py", line 21, in <module>
    from .app import Flask
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\wrappers\__init__.py)

**Comment by VahidTa** [comment]
Hi,

It seems you didn't install required packages. Please take a look into documentation:

https://fwmig.readthedocs.io/en/latest/installation.html

**Comment by theazlan89** [comment]
Its show "Requirement already satisfied"

**Comment by theazlan89** [comment]
Its resolved. After pip install werkzeug==2.0.3 and rerun requirements.

**Comment by VahidTa** [comment]
Fixed with [commit](https://github.com/VahidTa/firewall_migration_tool/commit/37f63f29680703cd44cc0214ecb0465f78b5ab66)
